// Generates content/docs/user/tools.mdx (and developer/plugin-api/tool-requirements.mdx, see below) from XIV MCP's own catalogs, so the tools reference always matches the code:
//   XivMcp.Core/Permissions/PermissionCatalog.cs   groups, their defaults and which core tool belongs to which
//   XivMcp.Core/Integrations/IntegrationCatalog.cs  the integrations and the capabilities of their tools
//   XivMcp.Core/Mcp/ToolSummaries.cs                the one-sentence description of each tool for players
//   XivMcp/Tools/*.cs                               which core tools change something (ReadOnly = false)
// Runs before `npm run dev` and `npm run build`. The output is not committed.
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const site = join(dirname(fileURLToPath(import.meta.url)), '..');
const repo = join(site, '..');
const read = (path) => readFileSync(join(repo, path), 'utf8');
const out = join(site, 'content', 'docs', 'user', 'tools.mdx');

const warnings = [];

// ToolSummaries: ["name"] = "text",
const summaries = new Map(
  [...read('XivMcp.Core/Mcp/ToolSummaries.cs').matchAll(/\["(\w+)"\] = "((?:[^"\\]|\\.)*)",/g)].map((m) => [m[1], m[2].replace(/\\"/g, '"')]),
);

// PermissionCatalog: the core groups, then the tool lists per group.
const catalog = read('XivMcp.Core/Permissions/PermissionCatalog.cs');
const mode = { A: 'Allow', D: 'Deny' };
const groups = [
  ...catalog.matchAll(/new\("(\w+)", "([^"]+)", "([^"]+)",\s*([AD]), ([AD])((?:, Has\w+: false)*)\)/g),
].map((m) => ({
  id: m[1],
  title: m[2],
  description: m[3],
  read: m[6].includes('HasRead: false') ? null : mode[m[4]],
  write: m[6].includes('HasWrite: false') ? null : mode[m[5]],
  tools: [],
}));
const coreTools = catalog.slice(catalog.indexOf('CoreTools'));
for (const m of coreTools.matchAll(/\["(\w+)"\] =\s*\[([^\]]*)\]/g)) {
  const group = groups.find((g) => g.id === m[1]);
  if (!group) {
    warnings.push(`PermissionCatalog lists tools for an unknown group '${m[1]}'.`);
    continue;
  }
  group.tools = [...m[2].matchAll(/"(\w+)"/g)].map((t) => t[1]);
}

// Core tools that change something: their definitions set ReadOnly = false (it defaults to true). Most are `Name = "x", …`;
// a few are made in a loop over `("x", …)` tuples with `Name = someVariable`, and then the loop's ReadOnly applies to each.
const changing = new Set();
const defined = new Set();
const sources = readdirSync(join(repo, 'XivMcp'), { recursive: true })
  .filter((f) => f.endsWith('.cs') && !/[\\/](bin|obj)[\\/]/.test(f))
  .map((f) => read(join('XivMcp', f)));
for (const code of sources) {
  for (const part of code.split(/\bName = "/).slice(1)) {
    const name = part.slice(0, part.indexOf('"'));
    defined.add(name);
    if (/\bReadOnly = false\b/.test(part.split(/\bName = /)[0])) changing.add(name);
  }
  for (const loop of code.matchAll(/foreach \(var \((\w+),[^)]*\) in new\[\]\s*\{([\s\S]*?)\}\)\s*\{([\s\S]*?)\n\s{8}\}/g)) {
    const [, variable, tuples, body] = loop;
    if (!new RegExp(`\\bName = ${variable}\\b`).test(body)) continue;
    for (const t of tuples.matchAll(/\(\s*"(\w+)"/g)) {
      defined.add(t[1]);
      if (/\bReadOnly = false\b/.test(body)) changing.add(t[1]);
    }
  }
}

// IntegrationCatalog: new("PluginId", "Display name", "Summary", ...{ ["tool"] = [Capabilities], ... })
const integrations = [];
const integrationSource = read('XivMcp.Core/Integrations/IntegrationCatalog.cs');
for (const m of integrationSource.matchAll(/new\("(\w+)", "([^"]+)", "([^"]+)", new Dictionary<string, string\[\]>\s*\{([^}]*)\}/g)) {
  const tools = [...m[4].matchAll(/\["(\w+)"\] = \[([^\]]*)\]/g)].map((t) => ({
    name: t[1],
    capabilities: t[2].split(',').map((c) => c.trim()).filter(Boolean).map(snake),
  }));
  integrations.push({ id: m[1], title: m[2], description: m[3], tools });
}

function snake(pascal) {
  return pascal.replace(/([a-z])([A-Z])/g, '$1_$2').toLowerCase();
}

if (groups.length === 0 || integrations.length === 0) throw new Error('generate-tools: could not read the catalogs; did their format change?');

// MDX treats { } < > as syntax; summaries are plain text.
const text = (s) => s.replace(/[{}<>]/g, (c) => `\\${c}`);
const summary = (name) => {
  const s = summaries.get(name);
  if (!s) warnings.push(`'${name}' has no entry in ToolSummaries.`);
  return s ? text(s) : '';
};
const chip = (label, value) => `<span className="xiv-chip">${label}: ${value}</span>`;

const lines = [];
const total = groups.reduce((n, g) => n + g.tools.length, 0) + integrations.reduce((n, i) => n + i.tools.length, 0);
lines.push(
  '---',
  'title: Tools reference',
  `description: All ${total} tools XIV MCP offers your assistant, by module, with what each one does.`,
  'icon: Wrench',
  '---',
  '',
  '{/* Generated by scripts/generate-tools.mjs from the C# catalogs on every build. Do not edit: change the code instead. */}',
  '',
  'Your assistant picks these tools on its own; you never call them yourself. This list shows what it can use, so you know what to ask for and which setting a tool follows.',
  '',
  '- **Reads** tools only look. They follow the *Reading* setting of their module (Allow, Ask or Deny).',
  '- **Changes** tools act in the game or edit something. They follow the *Changes* setting.',
  '- The chips under each module show its default settings. You change them in `/xivmcp` → **Modules**, see [Modules and permissions](/docs/user/permissions/modules).',
  '',
  '<Callout type="info">This page is generated from XIV MCP\'s own code on every build, so it always matches the version the documentation was built from.</Callout>',
  '',
);

lines.push('## Core modules', '');
for (const g of groups) {
  lines.push(`### ${g.title}`, '', g.description.replace(/\.$/, '') + '.', '');
  const chips = [g.read && chip('Reading', g.read), g.write && chip('Changes', g.write)].filter(Boolean);
  lines.push(`<div className="not-prose flex flex-wrap gap-1.5">${chips.join(' ')}</div>`, '');
  lines.push('| Tool | Kind | What it does |', '|---|---|---|');
  for (const t of g.tools) {
    if (!defined.has(t)) warnings.push(`'${t}' is in PermissionCatalog but no definition was found in XivMcp/Tools.`);
    lines.push(`| \`${t}\` | ${changing.has(t) ? 'Changes' : 'Reads'} | ${summary(t)} |`);
  }
  lines.push('');
}

lines.push(
  '## Integrations',
  '',
  'These modules drive one other plugin each. They are only offered while that plugin is loaded, and they have their own settings, independent of the core modules. A tool that changes something lists the [capabilities](/docs/developer/plugin-api/capabilities) it uses.',
  '',
);
for (const i of integrations) {
  const hasRead = i.tools.some((t) => t.capabilities.length === 0);
  const hasWrite = i.tools.some((t) => t.capabilities.length > 0);
  lines.push(`### ${i.title}`, '', i.description, '');
  const chips = [hasRead && chip('Reading', 'Allow'), hasWrite && chip('Changes', 'Deny')].filter(Boolean);
  lines.push(`<div className="not-prose flex flex-wrap gap-1.5">${chips.join(' ')}</div>`, '');
  lines.push('| Tool | Kind | What it does |', '|---|---|---|');
  for (const t of i.tools) {
    const kind = t.capabilities.length ? `Changes (${t.capabilities.map((c) => `\`${c}\``).join(', ')})` : 'Reads';
    lines.push(`| \`${t.name}\` | ${kind} | ${summary(t.name)} |`);
  }
  lines.push('');
}

lines.push(
  '## Tools from other plugins',
  '',
  'Plugins you install can add their own tools. They appear in `/xivmcp` → **Third-party plugins** once you enable them, not in this list. See [Third-party plugins](/docs/user/permissions/third-party).',
  '',
);

writeFileSync(out, lines.join('\n'));

// ------------------------------------------------------------------ tools that need plugins
// XivMcp.Core/Integrations/PluginCatalog.cs     the plugins and where to install them
// XivMcp.Core/Integrations/ToolRequirements.cs  which core tools use which plugin, and what for

const catalogSource = read('XivMcp.Core/Integrations/PluginCatalog.cs');
const known = new Map(
  [...catalogSource.matchAll(/new\("(\w+)", "([^"]+)", (?:"([^"]+)"|Official)\)/g)].map((m) => [
    m[1].toLowerCase(),
    { id: m[1], name: m[2], repo: m[3] ?? 'official' },
  ]),
);
const plugin = (id) => {
  const p = known.get(id.toLowerCase());
  if (!p) warnings.push(`'${id}' is used by a tool but missing from PluginCatalog.`);
  return p ?? { id, name: id, repo: 'official' };
};

const requirementSource = read('XivMcp.Core/Integrations/ToolRequirements.cs');
const coreBlock = requirementSource.slice(requirementSource.indexOf('Core {'));
const requirements = [...coreBlock.matchAll(/\["(\w+)"\] =\s*\[([\s\S]*?)\]\s*,/g)].map((m) => ({
  tool: m[1],
  needs: [...m[2].matchAll(/new\("(\w+)", ([NI]), "((?:[^"\\]|\\.)*)"\)/g)].map((n) => ({
    plugin: plugin(n[1]),
    needed: n[2] === 'N',
    purpose: n[3].replace(/\\"/g, '"'),
  })),
}));
if (known.size === 0 || requirements.length === 0) throw new Error('generate-tools: could not read PluginCatalog or ToolRequirements; did their format change?');

const repoCell = (r) => (r === 'official' ? "Dalamud's main repository" : `<span className="xiv-url">${r}</span>`);
const req = [];
req.push(
  '---',
  'title: Tools that need plugins',
  "description: Which of XIV MCP's tools use other plugins, what for, and where players get them.",
  'icon: Blocks',
  '---',
  '',
  '{/* Generated by scripts/generate-tools.mjs from PluginCatalog.cs, ToolRequirements.cs and IntegrationCatalog.cs on every build. */}',
  '',
  "Some of XIV MCP's own tools do their work through another plugin. When your jobs use one, declare it with `McpDependency.BuiltIn(\"tool\")`: XIV MCP checks these plugins for you and shows the player what is missing, with a way to install it. See [Using other tools in your jobs](/docs/developer/plugin-api/interop).",
  '',
  '- **Needed:** the tool, or the use named next to the plugin, fails without it. The player sees an error on your plugin\'s page.',
  '- **Improves:** the tool works without it and only does better with it. The player sees a hint, not an error.',
  '',
  '<Callout type="info">This page is generated from XIV MCP\'s own code on every build, so it always matches the version the documentation was built from.</Callout>',
  '',
  '## Core tools',
  '',
  '| Tool | What it does | Plugins it uses |',
  '|---|---|---|',
);
for (const r of requirements) {
  const uses = r.needs.map((n) => `**${n.plugin.name}** (${n.needed ? 'needed' : 'improves'}): ${text(n.purpose)}`).join('<br />');
  req.push(`| \`${r.tool}\` | ${summary(r.tool)} | ${uses} |`);
}
req.push(
  '',
  '## Integration tools',
  '',
  'These tools exist to drive one plugin each, so they always need it. They are only offered to the assistant while that plugin is loaded.',
  '',
);
for (const i of integrations) {
  req.push(`### ${i.title}`, '', `${text(i.description)} Needs **${plugin(i.id).name}**.`, '', '| Tool | What it does |', '|---|---|');
  for (const t of i.tools) req.push(`| \`${t.name}\` | ${summary(t.name)} |`);
  req.push('');
}
req.push(
  '## Where to get them',
  '',
  'Plugins outside Dalamud\'s main repository need their repository added first: Dalamud settings → **Experimental** → **Custom Plugin Repositories**. The Third-party plugins page offers to copy the URL and open those settings.',
  '',
  '| Plugin | Internal name | Repository |',
  '|---|---|---|',
  ...[...known.values()].map((p) => `| ${p.name} | \`${p.id}\` | ${repoCell(p.repo)} |`),
  '',
);
const reqOut = join(site, 'content', 'docs', 'developer', 'plugin-api', 'tool-requirements.mdx');
writeFileSync(reqOut, req.join('\n'));

for (const w of warnings) console.warn(`generate-tools: ${w}`);
console.log(`generate-tools: wrote ${total} tools to ${out.slice(site.length + 1)}`);
console.log(`generate-tools: wrote ${requirements.length} core tools and ${integrations.length} integrations to ${reqOut.slice(site.length + 1)}`);
